name: tolls
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  intl: ^0.19.0
  intl_phone_number_field: ^0.1.8
  pinput: ^4.0.0
  qr_scanner_overlay: ^0.0.2
  image_picker: ^1.0.7
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  top_snackbar_flutter: ^3.1.0
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  permission_handler: ^11.3.0
  mobile_scanner: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
  fonts:
    enabled: true

flutter_native_splash:
  background_image: assets/images/tolls.png
  android_12:
    color: "#ffffff"
    image: assets/images/tolls.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/tolls.png"
  remove_alpha_ios: true
  image_path_ios: "assets/images/tolls.png"
  ios: true
  min_sdk_android: 21
